In [15]:
import sys

!{sys.executable} -m pip install \
    pandas \
    numpy \
    openai \
    sentence-transformers \
    scikit-learn \
    networkx \
    pyvis \
    telethon \
    ipywidgets

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy in ./.venv/lib/python3.14/site-packages (2.4.6)
Requirement already satisfied: openai in ./.venv/lib/python3.14/site-packages (2.41.1)
Requirement already satisfied: sentence-transformers in ./.venv/lib/python3.14/site-packages (5.5.1)
Requirement already satisfied: scikit-learn in ./.venv/lib/python3.14/site-packages (1.9.0)
Requirement already satisfied: networkx in ./.venv/lib/python3.14/site-packages (3.6.1)
Requirement already satisfied: pyvis in ./.venv/lib/python3.14/site-packages (0.3.2)
Requirement already satisfied: telethon in ./.venv/lib/python3.14/site-packages (1.43.2)
Collecting ipywidgets
  Downloading ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: anyio<5,>=3.5.0 in ./.venv/lib/python3.14/site-packages (from openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in ./.venv/lib/python3.14/site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in ./.venv/lib/python3.14/site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in ./.venv/lib/python3.14/site-packages (from openai) (0.15.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in ./.venv/lib/python3.14/site-packages (from openai) (2.13.4)
Requirement already satisfied: sniffio in ./.venv/lib/python3.14/site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in ./.venv/lib/python3.14/site-packages (from openai) (4.68.2)
Requirement already satisfied: typing-extensions<5,>=4.11 in ./.venv/lib/python3.14/site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in ./.venv/lib/python3.14/site-packages (from anyio<5,>=3.5.0->openai) (3.18)
Requirement already satisfied: certifi in ./.venv/lib/python3.14/site-packages (from httpx<1,>=0.23.0->openai) (2026.5.20)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.14/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.14/site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in ./.venv/lib/python3.14/site-packages (from pydantic<3,>=1.9.0->openai) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in ./.venv/lib/python3.14/site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in ./.venv/lib/python3.14/site-packages (from sentence-transformers) (5.11.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in ./.venv/lib/python3.14/site-packages (from sentence-transformers) (1.19.0)
Requirement already satisfied: torch>=1.11.0 in ./.venv/lib/python3.14/site-packages (from sentence-transformers) (2.12.0)
Requirement already satisfied: scipy>=1.0.0 in ./.venv/lib/python3.14/site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.14/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in ./.venv/lib/python3.14/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in ./.venv/lib/python3.14/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./.venv/lib/python3.14/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in ./.venv/lib/python3.14/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in ./.venv/lib/python3.14/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: click>=8.4.0 in ./.venv/lib/python3.14/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in ./.venv/lib/python3.14/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.3)
Requirement already satisfied: fsspec>=2023.5.0 in ./.venv/lib/python3.14/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in ./.venv/lib/python3.14/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: shellingham>=1.3.0 in ./.venv/lib/python3.14/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in ./.venv/lib/python3.14/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in ./.venv/lib/python3.14/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: joblib>=1.4.0 in ./.venv/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in ./.venv/lib/python3.14/site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./.venv/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: ipython>=5.3.0 in ./.venv/lib/python3.14/site-packages (from pyvis) (9.14.1)
Requirement already satisfied: jinja2>=2.9.6 in ./.venv/lib/python3.14/site-packages (from pyvis) (3.1.6)
Requirement already satisfied: jsonpickle>=1.4.1 in ./.venv/lib/python3.14/site-packages (from pyvis) (4.1.2)
Requirement already satisfied: pyaes in ./.venv/lib/python3.14/site-packages (from telethon) (1.6.1)
Requirement already satisfied: rsa in ./.venv/lib/python3.14/site-packages (from telethon) (4.9.1)
Requirement already satisfied: comm>=0.1.3 in ./.venv/lib/python3.14/site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: traitlets>=4.3.1 in ./.venv/lib/python3.14/site-packages (from ipywidgets) (5.15.1)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets)
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: decorator>=5.1.0 in ./.venv/lib/python3.14/site-packages (from ipython>=5.3.0->pyvis) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in ./.venv/lib/python3.14/site-packages (from ipython>=5.3.0->pyvis) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in ./.venv/lib/python3.14/site-packages (from ipython>=5.3.0->pyvis) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in ./.venv/lib/python3.14/site-packages (from ipython>=5.3.0->pyvis) (0.2.2)
Requirement already satisfied: pexpect>4.6 in ./.venv/lib/python3.14/site-packages (from ipython>=5.3.0->pyvis) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in ./.venv/lib/python3.14/site-packages (from ipython>=5.3.0->pyvis) (3.0.52)
Requirement already satisfied: psutil>=7 in ./.venv/lib/python3.14/site-packages (from ipython>=5.3.0->pyvis) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in ./.venv/lib/python3.14/site-packages (from ipython>=5.3.0->pyvis) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in ./.venv/lib/python3.14/site-packages (from ipython>=5.3.0->pyvis) (0.6.3)
Requirement already satisfied: wcwidth in ./.venv/lib/python3.14/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.3.0->pyvis) (0.8.1)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in ./.venv/lib/python3.14/site-packages (from jedi>=0.18.2->ipython>=5.3.0->pyvis) (0.8.7)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.14/site-packages (from jinja2>=2.9.6->pyvis) (3.0.3)
Requirement already satisfied: ptyprocess>=0.5 in ./.venv/lib/python3.14/site-packages (from pexpect>4.6->ipython>=5.3.0->pyvis) (0.7.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.venv/lib/python3.14/site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Requirement already satisfied: executing>=1.2.0 in ./.venv/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython>=5.3.0->pyvis) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in ./.venv/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython>=5.3.0->pyvis) (3.0.1)
Requirement already satisfied: pure-eval in ./.venv/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython>=5.3.0->pyvis) (0.2.3)
Requirement already satisfied: setuptools<82 in ./.venv/lib/python3.14/site-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in ./.venv/lib/python3.14/site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./.venv/lib/python3.14/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: pyasn1>=0.1.3 in ./.venv/lib/python3.14/site-packages (from rsa->telethon) (0.6.3)
Downloading ipywidgets-8.1.8-py3-none-any.whl (139 kB)
Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 914.9/914.9 kB 5.0 MB/s  0:00:00m 5.4 MB/s eta 0:00:01
Downloading widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 4.8 MB/s  0:00:004.6 MB/s eta 0:00:01
Installing collected packages: widgetsnbextension, jupyterlab_widgets, ipywidgets
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [ipywidgets]
Successfully installed ipywidgets-8.1.8 jupyterlab_widgets-3.0.16 widgetsnbextension-4.0.15

In [16]:
import pandas as pd
import numpy as np
import networkx as nx
from pyvis.network import Network
from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans

print("All packages imported successfully")

All packages imported successfully

In [17]:
API_ID = 33950223
API_HASH = "e7cebfb1808375747e838058be8ea2e9"

In [18]:
from telethon import TelegramClient

client = TelegramClient(
    "telegram_session",
    API_ID,
    API_HASH
)

await client.start()

me = await client.get_me()

print("Connected successfully")
print(me.first_name)

Connected successfully
Kkkk

Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 60] Operation timed out
Graceful disconnection timed out, forcibly ignoring cleanup
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 60] Operation timed out
Graceful disconnection timed out, forcibly ignoring cleanup
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 60] Operation timed out
Graceful disconnection timed out, forcibly ignoring cleanup
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 60] Operation timed out
Graceful disconnection timed out, forcibly ignoring cleanup
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 60] Operation timed out
Graceful disconnection timed out, forcibly ignoring cleanup
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 60] Operation timed out
Graceful disconnection timed out, forcibly ignoring cleanup
Server resent the older message 7650870469200652289, ignoring
Server sent a very old message with ID 7650871313563757569, ignoring (see FAQ for details)
Server sent a very old message with ID 7650871510211910657, ignoring (see FAQ for details)
Server sent a very old message with ID 7650872005096648705, ignoring (see FAQ for details)
Server sent a very old message with ID 7650872069799044097, ignoring (see FAQ for details)
Server sent a very old message with ID 7650872224403569665, ignoring (see FAQ for details)
Server sent a very old message with ID 7650872277454519297, ignoring (see FAQ for details)
Server sent a very old message with ID 7650872295592469505, ignoring (see FAQ for details)
Server sent a very old message with ID 7650872563682298881, ignoring (see FAQ for details)
Server sent a very old message with ID 7650872625249241089, ignoring (see FAQ for details)
Server sent a very old message with ID 7650872653640235009, ignoring (see FAQ for details)
Security error while unpacking a received message: Too many messages had to be ignored consecutively
Server sent a very old message with ID 7650872658243809281, ignoring (see FAQ for details)
Security error while unpacking a received message: Too many messages had to be ignored consecutively
Server sent a very old message with ID 7650873518326289409, ignoring (see FAQ for details)
Security error while unpacking a received message: Too many messages had to be ignored consecutively
Server closed the connection: [Errno 54] Connection reset by peer
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 49] Can't assign requested address
Server resent the older message 7650958180509798401, ignoring
Server closed the connection: [Errno 54] Connection reset by peer
Server resent the older message 7651005054547087361, ignoring
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Server resent the older message 7651029220998330369, ignoring
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Server resent the older message 7651072320067771393, ignoring
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Server resent the older message 7651180215909357569, ignoring
Server closed the connection: [Errno 54] Connection reset by peer
Server resent the older message 7651211548235124737, ignoring
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Server resent the older message 7651232062817854465, ignoring
Server closed the connection: [Errno 54] Connection reset by peer
Server resent the older message 7651281542585213953, ignoring
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Server resent the older message 7651324086795222017, ignoring
Server closed the connection: [Errno 49] Can't assign requested address
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 60] Operation timed out
Graceful disconnection timed out, forcibly ignoring cleanup
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 60] Operation timed out
Graceful disconnection timed out, forcibly ignoring cleanup
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 60] Operation timed out
Graceful disconnection timed out, forcibly ignoring cleanup
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server sent a very old message with ID 7651540401226628097, ignoring (see FAQ for details)
Server sent a very old message with ID 7651540568511488001, ignoring (see FAQ for details)
Server sent a very old message with ID 7651540793365825537, ignoring (see FAQ for details)
Server sent a very old message with ID 7651540801705586689, ignoring (see FAQ for details)
Server sent a very old message with ID 7651541039577070593, ignoring (see FAQ for details)
Server sent a very old message with ID 7651541143380972545, ignoring (see FAQ for details)
Server sent a very old message with ID 7651541163936458753, ignoring (see FAQ for details)
Server sent a very old message with ID 7651541182042129409, ignoring (see FAQ for details)
Server sent a very old message with ID 7651541188245866497, ignoring (see FAQ for details)
Server sent a very old message with ID 7651541201722062849, ignoring (see FAQ for details)
Security error while unpacking a received message: Too many messages had to be ignored consecutively
Server sent a very old message with ID 7651541233855737857, ignoring (see FAQ for details)
Security error while unpacking a received message: Too many messages had to be ignored consecutively
Server sent a very old message with ID 7651541737056087041, ignoring (see FAQ for details)
Security error while unpacking a received message: Too many messages had to be ignored consecutively
Server sent a very old message with ID 7651541783745996801, ignoring (see FAQ for details)
Security error while unpacking a received message: Too many messages had to be ignored consecutively
Server closed the connection: [Errno 54] Connection reset by peer
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 60] Operation timed out
Graceful disconnection timed out, forcibly ignoring cleanup
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 54] Connection reset by peer
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 60] Operation timed out
Graceful disconnection timed out, forcibly ignoring cleanup
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Server closed the connection: [Errno 60] Operation timed out
Graceful disconnection timed out, forcibly ignoring cleanup
Error executing high-level request after reconnect: <class 'sqlite3.OperationalError'>: database is locked
Cannot get difference since the account is likely misusing the session: database is locked
Unhandled exception from keepalive_handle after cancelling <class '_asyncio.Task'> (<Task finished name='Task-142' coro=<UpdateMethods._keepalive_loop() done, defined at /Users/pratapgurung/OSINT/.venv/lib/python3.14/site-packages/telethon/client/updates.py:516> exception=OperationalError('database is locked')>)
Traceback (most recent call last):
  File "/Users/pratapgurung/OSINT/.venv/lib/python3.14/site-packages/telethon/helpers.py", line 176, in _cancel
    await task
  File "/Users/pratapgurung/OSINT/.venv/lib/python3.14/site-packages/telethon/client/updates.py", line 552, in _keepalive_loop
    await self._save_states_and_entities()
  File "/Users/pratapgurung/OSINT/.venv/lib/python3.14/site-packages/telethon/client/telegrambaseclient.py", line 709, in _save_states_and_entities
    self.session.process_entities(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        types.contacts.ResolvedPeer(None, [types.InputPeerUser(0, self._mb_entity_cache.self_id)], [])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/pratapgurung/OSINT/.venv/lib/python3.14/site-packages/telethon/sessions/sqlite.py", line 318, in process_entities
    c.executemany(
    ~~~~~~~~~~~~~^
        'insert or replace into entities values (?,?,?,?,?,?)', rows)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked
OperationalError exception in shielded future
future: <Task finished name='Task-801' coro=<TelegramBaseClient._disconnect_coro() done, defined at /Users/pratapgurung/OSINT/.venv/lib/python3.14/site-packages/telethon/client/telegrambaseclient.py:724> exception=OperationalError('database is locked')>
Traceback (most recent call last):
  File "/Users/pratapgurung/OSINT/.venv/lib/python3.14/site-packages/telethon/client/telegrambaseclient.py", line 754, in _disconnect_coro
    await self._save_states_and_entities()
  File "/Users/pratapgurung/OSINT/.venv/lib/python3.14/site-packages/telethon/client/telegrambaseclient.py", line 709, in _save_states_and_entities
    self.session.process_entities(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        types.contacts.ResolvedPeer(None, [types.InputPeerUser(0, self._mb_entity_cache.self_id)], [])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/pratapgurung/OSINT/.venv/lib/python3.14/site-packages/telethon/sessions/sqlite.py", line 318, in process_entities
    c.executemany(
    ~~~~~~~~~~~~~^
        'insert or replace into entities values (?,?,?,?,?,?)', rows)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

In [19]:
async def test_channel():
    await client.start()

    channel = await client.get_entity("telegram")

    print(f"Channel: {channel.title}")

    async for msg in client.iter_messages(channel, limit=5):
        print("=" * 80)
        print(msg.date)
        print(msg.text)

await test_channel()

Channel: Telegram News
================================================================================
2026-05-14 16:09:50+00:00
For all the features from this update, like **statistics** and **custom limits** for polls, **streaming text** for bots, **silent scheduled messages** and more – check out the full blog:
https://telegram.org/blog/ai-bot-revolution-11-new-features

May Features
[1](https://t.me/telegram/440) • [2](https://t.me/telegram/441) • [3](https://t.me/telegram/442) • [4](https://t.me/telegram/443) • [5](https://t.me/telegram/444) • **More**
================================================================================
2026-05-14 16:09:39+00:00
**Expanded Emoji and Sticker Search.** Over **100 million** emoji and stickers can now be found via the **search function** in the sticker panel.

May Features
[1](https://t.me/telegram/440) • [2](https://t.me/telegram/441) • [3](https://t.me/telegram/442) • [4](https://t.me/telegram/443) • **5** • [More](https://t.me/telegram/445)
================================================================================
2026-05-14 16:09:19+00:00
**Custom AI Styles.** The [text editor](https://t.me/telegram/435) allows anyone to use **their own prompts** to build **unique styles**.

Each custom style has a **shareable link** so others users can add it to their editor.

May Features
[1](https://t.me/telegram/440) • [2](https://t.me/telegram/441) • [3](https://t.me/telegram/442) • **4** • [5](https://t.me/telegram/444) • [More](https://t.me/telegram/445)
================================================================================
2026-05-14 16:08:52+00:00
**Chat Automation in Profiles.** Every Telegram user can now **connect a bot **to their profile – and let it **respond to messages** on their behalf.

May Features
[1](https://t.me/telegram/440) • [2](https://t.me/telegram/441) • **3** • [4](https://t.me/telegram/443) • [5](https://t.me/telegram/444) • [More](https://t.me/telegram/445)
================================================================================
2026-05-14 16:08:31+00:00
**Bot-to-Bot Communication.** Bots are now able to respond to **other bots**, not just users.

AI enthusiasts can utilize this to create **custom workflows** with **autonomous agents**.

May Features
[1](https://t.me/telegram/440) • **2** • [3](https://t.me/telegram/442) • [4](https://t.me/telegram/443) • [5](https://t.me/telegram/444) • [More](https://t.me/telegram/445)

In [7]:
async def search_channel(channel_name, query, limit=50):
    await client.start()

    channel = await client.get_entity(channel_name)

    results = []

    async for msg in client.iter_messages(
        channel,
        search=query,
        limit=limit
    ):
        results.append({
            "date": msg.date,
            "text": msg.text,
            "views": getattr(msg, "views", None)
        })

    return results

In [8]:
results = await search_channel(
    "cnnnews18live",
    "India"
)

len(results)

50

In [9]:
import pandas as pd
import re

def extract_urls(text):
    if not text:
        return []
    return re.findall(r'https?://\S+|t\.me/\S+', text)

async def collect_channel_messages(channel_name, search=None, limit=100):
    await client.start()
    channel = await client.get_entity(channel_name)

    rows = []

    async for msg in client.iter_messages(
        channel,
        search=search,
        limit=limit
    ):
        text = msg.text or ""

        rows.append({
            "channel": channel_name,
            "message_id": msg.id,
            "date": msg.date,
            "text": text,
            "views": getattr(msg, "views", None),
            "forwards": getattr(msg, "forwards", None),
            "reply_to_msg_id": getattr(msg, "reply_to_msg_id", None),
            "has_media": msg.media is not None,
            "urls": extract_urls(text),
            "message_link": f"https://t.me/{channel_name}/{msg.id}"
        })

    return pd.DataFrame(rows)

In [10]:
df = await collect_channel_messages(
    "cnnnews18live",
    search="India Pakistan War",
    limit=500
)

df.head()

,channel,message_id,date,text,views,forwards,reply_to_msg_id,has_media,urls,message_link
0,cnnnews18live,230089,2026-06-10 04:07:06+00:00,PoK On The Boil: Why Deadly Protests Have Trig...,1,0,None,True,[https://t.co/u9beGuKpbY],https://t.me/cnnnews18live/230089
1,cnnnews18live,219268,2026-05-08 14:33:16+00:00,"#OpSindoor | For the first time, China has con...",4,0,None,True,"[https://t.co/Njp76QNyEf, https://t.co/Q4AHy15...",https://t.me/cnnnews18live/219268
2,cnnnews18live,218826,2026-05-07 13:42:30+00:00,#OpSindoor | This is not the end — it is only ...,3,0,None,True,[],https://t.me/cnnnews18live/218826
3,cnnnews18live,207383,2026-04-06 18:50:57+00:00,#BreakingNews | US President Donald Trump reit...,6,0,None,True,[https://t.co/oT79hVDV90],https://t.me/cnnnews18live/207383
4,cnnnews18live,207381,2026-04-06 18:40:44+00:00,#BreakingNews | God is support US in this conf...,4,0,None,True,[https://t.co/t8n9FWN38b],https://t.me/cnnnews18live/207381

In [11]:
df[["date", "text", "views", "forwards", "message_link"]].head(10)

,date,text,views,forwards,message_link
0,2026-06-10 04:07:06+00:00,PoK On The Boil: Why Deadly Protests Have Trig...,1,0,https://t.me/cnnnews18live/230089
1,2026-05-08 14:33:16+00:00,"#OpSindoor | For the first time, China has con...",4,0,https://t.me/cnnnews18live/219268
2,2026-05-07 13:42:30+00:00,#OpSindoor | This is not the end — it is only ...,3,0,https://t.me/cnnnews18live/218826
3,2026-04-06 18:50:57+00:00,#BreakingNews | US President Donald Trump reit...,6,0,https://t.me/cnnnews18live/207383
4,2026-04-06 18:40:44+00:00,#BreakingNews | God is support US in this conf...,4,0,https://t.me/cnnnews18live/207381
5,2026-03-28 07:34:38+00:00,#IndiaUS | ‘Threatened With 250% Tariff’: Trum...,3,0,https://t.me/cnnnews18live/204077
6,2026-03-27 04:17:48+00:00,‘Trump Will Listen To Modi’: US War Expert Bac...,4,0,https://t.me/cnnnews18live/203630
7,2026-03-26 15:57:58+00:00,#IndiaPakistan | The political ripples of West...,3,0,https://t.me/cnnnews18live/203542
8,2026-03-22 02:03:23+00:00,#BreakingNews | Abdul Basit Sparks Row With “B...,3,0,https://t.me/cnnnews18live/202988
9,2026-03-18 01:51:27+00:00,News 18 Daily Digest | Iran Confirms: Ali Lari...,6,0,https://t.me/cnnnews18live/201621

In [12]:
df.sort_values("views", ascending=False)[
    ["date", "views", "forwards", "text", "message_link"]
].head(10)

,date,views,forwards,text,message_link
53,2025-08-11 16:24:15+00:00,61,0,#Exclusive | These utterly irresponsible and n...,https://t.me/cnnnews18live/130450
49,2025-08-15 00:15:21+00:00,46,0,"#WATCH | Washington DC | ""6-7 planes were knoc...",https://t.me/cnnnews18live/131733
50,2025-08-13 02:17:38+00:00,43,0,#Trending | The US State Department is patting...,https://t.me/cnnnews18live/130867
48,2025-08-18 18:36:46+00:00,38,0,Trump has once again claimed that he stopped I...,https://t.me/cnnnews18live/133052
59,2025-08-05 16:52:08+00:00,35,0,#WATCH | India Recalls 1971 War To Highlight U...,https://t.me/cnnnews18live/128254
62,2025-07-28 16:25:29+00:00,34,0,Donald Trump yet again claimed that if he had ...,https://t.me/cnnnews18live/124828
52,2025-08-11 17:15:02+00:00,27,0,"Bilawal Bhutto, ex-Pakistan foreign minister t...",https://t.me/cnnnews18live/130462
57,2025-08-11 05:18:03+00:00,25,0,Pakistan Field Marshal and Army chief Asim Mun...,https://t.me/cnnnews18live/130158
60,2025-08-04 01:55:33+00:00,24,0,“Stopped a lot of wars…” Trump persists in cla...,https://t.me/cnnnews18live/127283
51,2025-08-12 08:36:05+00:00,22,0,A deepfake video falsely showing General Dwive...,https://t.me/cnnnews18live/130666

In [20]:
df.tail()

,channel,message_id,date,text,views,forwards,reply_to_msg_id,has_media,urls,message_link
183,cnnnews18live,50198,2024-12-16 01:46:17+00:00,Vijay Diwas is celebrated every year on Decemb...,4,0,None,True,[https://t.co/zZWwK6QE6g],https://t.me/cnnnews18live/50198
184,cnnnews18live,24842,2024-09-07 12:26:31+00:00,"#BreakingNews: For the first time, Pakistan Ar...",3,0,None,False,[https://t.co/GuxFvi8kNR],https://t.me/cnnnews18live/24842
185,cnnnews18live,12843,2024-07-26 10:03:36+00:00,25 Years Of Kargil War: Fighting Tough Terrain...,1,0,None,True,[https://t.co/QWlrw5TE6A],https://t.me/cnnnews18live/12843
186,cnnnews18live,9169,2024-07-12 15:25:32+00:00,'Pakistan has been used by the west in the col...,1,0,None,False,[https://t.co/E6XD6MbBlu],https://t.me/cnnnews18live/9169
187,cnnnews18live,5312,2024-06-28 04:58:48+00:00,The expedition marks the 25th anniversary of I...,1,0,None,True,"[https://t.co/G14qMR6Mwt, https://t.co/yqmIcGf...",https://t.me/cnnnews18live/5312

In [13]:
print("Messages collected:", len(df))
print("Date range:", df["date"].min(), "to", df["date"].max())
print("Total views:", df["views"].fillna(0).sum())
print("Average views:", df["views"].fillna(0).mean())

Messages collected: 188
Date range: 2024-06-28 04:58:48+00:00 to 2026-06-10 04:07:06+00:00
Total views: 1189
Average views: 6.324468085106383

In [21]:
# ============================================================
# STEP 1: Clean and prepare Telegram messages
# ============================================================

import pandas as pd
import re

# Make a copy so we do not accidentally damage the original df
messages = df.copy()

# Ensure the date column is treated as datetime
messages["date"] = pd.to_datetime(messages["date"], errors="coerce")

# Remove rows with empty or missing text
messages["text"] = messages["text"].fillna("").astype(str)
messages = messages[messages["text"].str.strip() != ""]

# Remove duplicate messages, if any
messages = messages.drop_duplicates(subset=["message_id", "text"])

# Basic text cleaning for analysis
def clean_text(text):
    """
    Cleans Telegram message text while keeping useful OSINT signals.
    We remove excessive whitespace but keep hashtags, URLs, names, etc.
    """
    text = re.sub(r"\s+", " ", text)
    return text.strip()

messages["clean_text"] = messages["text"].apply(clean_text)

# Add simple helper fields
messages["text_length"] = messages["clean_text"].str.len()
messages["word_count"] = messages["clean_text"].str.split().str.len()
messages["date_only"] = messages["date"].dt.date
messages["hour"] = messages["date"].dt.hour

print("Original rows:", len(df))
print("Clean usable messages:", len(messages))
print("Date range:", messages["date"].min(), "to", messages["date"].max())

messages[["date", "clean_text", "views", "forwards", "message_link"]].head(5)

Original rows: 188
Clean usable messages: 188
Date range: 2024-06-28 04:58:48+00:00 to 2026-06-10 04:07:06+00:00

,date,clean_text,views,forwards,message_link
0,2026-06-10 04:07:06+00:00,PoK On The Boil: Why Deadly Protests Have Trig...,1,0,https://t.me/cnnnews18live/230089
1,2026-05-08 14:33:16+00:00,"#OpSindoor | For the first time, China has con...",4,0,https://t.me/cnnnews18live/219268
2,2026-05-07 13:42:30+00:00,#OpSindoor | This is not the end — it is only ...,3,0,https://t.me/cnnnews18live/218826
3,2026-04-06 18:50:57+00:00,#BreakingNews | US President Donald Trump reit...,6,0,https://t.me/cnnnews18live/207383
4,2026-04-06 18:40:44+00:00,#BreakingNews | God is support US in this conf...,4,0,https://t.me/cnnnews18live/207381

1. Understand channel vocabulary
2. Understand channel sources
3. Understand posting behaviour
4. Understand entities
5. THEN do narrative clustering

In [22]:
# ============================================================
# STEP 2: Find most common words in the channel
# ============================================================

from collections import Counter
import re

# Common words that add little intelligence value
STOP_WORDS = {
    "the","a","an","and","or","but","of","to","in","on","for",
    "with","at","by","from","is","are","was","were","be","been",
    "has","have","had","that","this","it","its","as","after",
    "about","into","their","they","them","will","would","can",
    "could","should","may","might","you","your","we","our"
}

all_words = []

for text in messages["clean_text"]:

    # Extract words
    words = re.findall(r"\b[a-zA-Z]{3,}\b", text.lower())

    # Remove stop words
    words = [w for w in words if w not in STOP_WORDS]

    all_words.extend(words)

word_counts = Counter(all_words)

top_words = word_counts.most_common(50)

for word, count in top_words:
    print(f"{word:<20} {count}")

india                287
pakistan             286
https                208
war                  194
operationsindoor     64
watch                45
trump                44
china                31
between              27
anchoranandn         24
indiapakistanwar     24
donaldtrump          22
face                 22
indiapakistan        21
pahalgamterrorattack 21
defence              20
during               19
not                  19
only                 19
changed              18
account              18
wars                 18
most                 18
terror               17
rshivshankar         17
more                 17
nuclear              17
definitive           17
unfolded             17
brought              17
knees                17
pahalgam             17
set                  16
reminder             16
insideoperationsindoor 16
former               15
all                  15
brasstacks           15
cnn                  15
breakingnews         14
what                 14
says                 14
details              14
major                14
donald               13
his                  13
water                13
here                 13
conflict             12
unitedstates         12

In [23]:
# ============================================================
# STEP 3: Extract hashtags
# ============================================================

hashtags = []

for text in messages["clean_text"]:
    hashtags.extend(
        re.findall(r"#(\w+)", text)
    )

hashtag_counts = Counter(hashtags)

print("Top hashtags:\n")

for tag, count in hashtag_counts.most_common(30):
    print(f"#{tag:<25} {count}")

Top hashtags:

#Pakistan                  64
#OperationSindoor          62
#India                     42
#Zakka_Jacob               30
#AnchorAnandN              24
#IndiaPakistanWar          23
#DonaldTrump               22
#IndiaPakistan             21
#PahalgamTerrorAttack      21
#ShivaniGupta_5            16
#RShivshankar              16
#InsideOperationSindoor    16
#BrassTacks                15
#BreakingNews              14
#Trump                     11
#UnitedStates              11
#PMModi                    11
#IndiaPakistanTensions     11
#Pahalgam                  11
#PahalgamTerroristAttack   11
#akankshaswarups           7
#siddhantvm                7
#WATCH                     7
#China                     7
#IndianArmy                7
#PlainSpeak                6
#AsimMunir                 6
#Manik_M_Jolly             6
#PlainSpeakPodcast         6
#pakistan                  5

In [24]:
# ============================================================
# STEP 4: Find referenced websites
# ============================================================

from urllib.parse import urlparse

domains = []

for urls in messages["urls"]:
    
    if not urls:
        continue

    for url in urls:
        try:
            domain = urlparse(url).netloc
            domain = domain.replace("www.", "")
            domains.append(domain)
        except:
            pass

domain_counts = Counter(domains)

print("Top referenced domains:\n")

for domain, count in domain_counts.most_common(20):
    print(f"{domain:<40} {count}")

Top referenced domains:

t.co                                     208

In [25]:
import sys

!{sys.executable} -m pip install spacy

Collecting spacy
  Downloading spacy-3.8.13-cp314-cp314-macosx_11_0_arm64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp314-cp314-macosx_11_0_arm64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp314-cp314-macosx_11_0_arm64.whl.metadata (9.7 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.13-cp314-cp314-macosx_11_0_arm64.whl.metadata (5.2 kB)
Collecting thinc<8.4.0,>=8.3.12 (from spacy)
  Downloading thinc-8.3.13-cp314-cp314-macosx_11_0_arm64.whl.metadata (14 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.5.3 (from spacy)
  Downloading srsly-2.5.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<2.0.0,>=1.0.0 (from spacy)
  Downloading weasel-1.0.0-py3-none-any.whl.metadata (4.6 kB)
Collecting confection<2.0.0,>=1.3.2 (from spacy)
  Downloading confection-1.3.3-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in ./.venv/lib/python3.14/site-packages (from spacy) (0.25.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in ./.venv/lib/python3.14/site-packages (from spacy) (4.68.2)
Requirement already satisfied: numpy>=1.19.0 in ./.venv/lib/python3.14/site-packages (from spacy) (2.4.6)
Collecting requests<3.0.0,>=2.13.0 (from spacy)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in ./.venv/lib/python3.14/site-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.14/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in ./.venv/lib/python3.14/site-packages (from spacy) (81.0.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.14/site-packages (from spacy) (26.2)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.14/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in ./.venv/lib/python3.14/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in ./.venv/lib/python3.14/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in ./.venv/lib/python3.14/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Collecting charset_normalizer<4,>=2 (from requests<3.0.0,>=2.13.0->spacy)
  Downloading charset_normalizer-3.4.7-cp314-cp314-macosx_10_15_universal2.whl.metadata (40 kB)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.14/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)
Collecting urllib3<3,>=1.26 (from requests<3.0.0,>=2.13.0->spacy)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.14/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.5.20)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.12->spacy)
  Downloading blis-1.3.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (7.5 kB)
Requirement already satisfied: click>=8.2.1 in ./.venv/lib/python3.14/site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.4.1)
Requirement already satisfied: shellingham>=1.3.0 in ./.venv/lib/python3.14/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in ./.venv/lib/python3.14/site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in ./.venv/lib/python3.14/site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Collecting cloudpathlib>=0.7.0 (from weasel<2.0.0,>=1.0.0->spacy)
  Downloading cloudpathlib-0.24.0-py3-none-any.whl.metadata (16 kB)
Collecting smart-open>=5.2.1 (from weasel<2.0.0,>=1.0.0->spacy)
  Downloading smart_open-7.6.1-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: httpx>=0.24.0 in ./.venv/lib/python3.14/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in ./.venv/lib/python3.14/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.14/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.14/site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.venv/lib/python3.14/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.venv/lib/python3.14/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting wrapt (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy)
  Downloading wrapt-2.2.1-cp314-cp314-macosx_11_0_arm64.whl.metadata (7.4 kB)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.14/site-packages (from jinja2->spacy) (3.0.3)
Downloading spacy-3.8.13-cp314-cp314-macosx_11_0_arm64.whl (6.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 45.4 MB/s  0:00:00 47.9 MB/s eta 0:00:01
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading confection-1.3.3-py3-none-any.whl (35 kB)
Downloading cymem-2.0.13-cp314-cp314-macosx_11_0_arm64.whl (42 kB)
Downloading murmurhash-1.0.15-cp314-cp314-macosx_11_0_arm64.whl (27 kB)
Downloading preshed-3.0.13-cp314-cp314-macosx_11_0_arm64.whl (138 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.4.7-cp314-cp314-macosx_10_15_universal2.whl (309 kB)
Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.3-cp314-cp314-macosx_11_0_arm64.whl (660 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.0/661.0 kB 42.4 MB/s  0:00:00
Downloading thinc-8.3.13-cp314-cp314-macosx_11_0_arm64.whl (792 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 792.1/792.1 kB 31.6 MB/s  0:00:00
Downloading blis-1.3.3-cp314-cp314-macosx_11_0_arm64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 39.8 MB/s  0:00:00
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-1.0.0-py3-none-any.whl (50 kB)
Downloading cloudpathlib-0.24.0-py3-none-any.whl (63 kB)
Downloading smart_open-7.6.1-py3-none-any.whl (64 kB)
Downloading wrapt-2.2.1-cp314-cp314-macosx_11_0_arm64.whl (81 kB)
Installing collected packages: wrapt, wasabi, urllib3, spacy-loggers, spacy-legacy, murmurhash, cymem, confection, cloudpathlib, charset_normalizer, catalogue, blis, srsly, smart-open, requests, preshed, thinc, weasel, spacy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/19 [spacy]8;5;237m━━ 18/19 [spacy]athlib]
Successfully installed blis-1.3.3 catalogue-2.0.10 charset_normalizer-3.4.7 cloudpathlib-0.24.0 confection-1.3.3 cymem-2.0.13 murmurhash-1.0.15 preshed-3.0.13 requests-2.34.2 smart-open-7.6.1 spacy-3.8.13 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.3 thinc-8.3.13 urllib3-2.7.0 wasabi-1.1.3 weasel-1.0.0 wrapt-2.2.1

In [26]:
import sys

!{sys.executable} -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 10.7 MB/s  0:00:013 MB/s eta 0:00:01:01
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [27]:
# ============================================================
# STEP 5A: Load spaCy
# ============================================================

import spacy

nlp = spacy.load("en_core_web_sm")

print("spaCy loaded")

spaCy loaded

In [28]:
# ============================================================
# STEP 5B: Extract entities
# ============================================================

from collections import Counter

people = Counter()
orgs = Counter()
locations = Counter()

for text in messages["clean_text"]:

    doc = nlp(text)

    for ent in doc.ents:

        if ent.label_ == "PERSON":
            people[ent.text] += 1

        elif ent.label_ == "ORG":
            orgs[ent.text] += 1

        elif ent.label_ in ["GPE", "LOC"]:
            locations[ent.text] += 1

In [29]:
print("\nTOP PEOPLE\n")

for name, count in people.most_common(20):
    print(f"{name:<30} {count}")

TOP PEOPLE

AnchorAnandN                   17
DonaldTrump                    14
Donald Trump                   10
Pakistan                       9
RShivshankar Set               9
IndiaPakistan                  8
Zakka_Jacob                    8
Trump                          7
PlainSpeakPodcast              6
PlainSpeak                     5
OPINION                        4
UnitedStates                   4
Asim Munir                     4
OpSindoor                      3
OperationSindoor               3
Tom Cooper                     3
LtGenDPPandey                  3
AmbRajivDogra                  3
GrihaAtul                      3
Lt Gen                         3

In [30]:
print("\nTOP ORGANIZATIONS\n")

for org, count in orgs.most_common(20):
    print(f"{org:<40} {count}")

TOP ORGANIZATIONS

OperationSindoor                         46
CNN                                      15
BreakingNews                             12
Trump                                    6
Major Manik M Jolly                      6
Army                                     4
Operation Sindoor                        3
Corps of Indian Army                     3
the Bangladesh Liberation War            3
GlobalPolitics                           2
Reuters                                  2
OperationSindoor Exposes Nexus           2
Fighter Pilot                            2
Pak                                      2
Congress                                 2
Pakistan Army                            2
Hamas                                    2
Pak PM's                                 1
Pak PM                                   1
US War Expert Backs India                1

In [31]:
print("\nTOP LOCATIONS\n")

for place, count in locations.most_common(20):
    print(f"{place:<30} {count}")

TOP LOCATIONS

India                          251
Pakistan                       203
China                          29
US                             17
Kashmir                        8
Afghanistan                    6
Iran                           5
Israel                         5
Turkey                         4
Bangladesh                     3
Kargil                         3
West Asia                      2
America                        2
Russia                         2
U.S.                           2
New Delhi                      2
Islamabad                      2
Indrabalan                     2
Centre                         2
West Asia Mediation            1

In [32]:
channel_profile = {
    "messages": len(messages),
    "top_people": people.most_common(10),
    "top_orgs": orgs.most_common(10),
    "top_locations": locations.most_common(10)
}

channel_profile

{'messages': 188,
 'top_people': [('AnchorAnandN', 17),
  ('DonaldTrump', 14),
  ('Donald Trump', 10),
  ('Pakistan', 9),
  ('RShivshankar Set', 9),
  ('IndiaPakistan', 8),
  ('Zakka_Jacob', 8),
  ('Trump', 7),
  ('PlainSpeakPodcast', 6),
  ('PlainSpeak', 5)],
 'top_orgs': [('OperationSindoor', 46),
  ('CNN', 15),
  ('BreakingNews', 12),
  ('Trump', 6),
  ('Major Manik M Jolly', 6),
  ('Army', 4),
  ('Operation Sindoor', 3),
  ('Corps of Indian Army', 3),
  ('the Bangladesh Liberation War', 3),
  ('GlobalPolitics', 2)],
 'top_locations': [('India', 251),
  ('Pakistan', 203),
  ('China', 29),
  ('US', 17),
  ('Kashmir', 8),
  ('Afghanistan', 6),
  ('Iran', 5),
  ('Israel', 5),
  ('Turkey', 4),
  ('Bangladesh', 3)]}

In [33]:
# ============================================================
# STEP 6A: Load embedding model
# ============================================================

from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("Model loaded")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 11257.97it/s]

Model loaded

In [34]:
# ============================================================
# STEP 6B: Convert messages into vectors
# ============================================================

texts = messages["clean_text"].tolist()

embeddings = model.encode(
    texts,
    show_progress_bar=True,
    convert_to_numpy=True
)

print("Embedding shape:", embeddings.shape)

Batches: 100%|███████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.91it/s]

Embedding shape: (188, 384)

In [35]:
# ============================================================
# STEP 7A: Cluster messages
# ============================================================

from sklearn.cluster import KMeans

NUM_CLUSTERS = 8

kmeans = KMeans(
    n_clusters=NUM_CLUSTERS,
    random_state=42,
    n_init=10
)

messages["cluster"] = kmeans.fit_predict(
    embeddings
)

print(
    messages["cluster"].value_counts()
)

cluster
0    59
1    41
2    20
6    18
4    18
5    15
7    10
3     7
Name: count, dtype: int64

In [36]:
# ============================================================
# STEP 8A: Review cluster examples
# ============================================================

for cluster_id in sorted(messages["cluster"].unique()):

    print("\n" + "=" * 80)
    print(f"CLUSTER {cluster_id}")
    print("=" * 80)

    sample = messages[
        messages["cluster"] == cluster_id
    ]["clean_text"].head(5)

    for msg in sample:
        print("\n•", msg[:300])

================================================================================
CLUSTER 0
================================================================================

• PoK On The Boil: Why Deadly Protests Have Triggered An India-Pakistan War Of Words #Pakistan #PoK #IndiaPakistan https://t.co/u9beGuKpbY

• #OpSindoor | This is not the end — it is only a pause. Pakistan is likely to return with another provocation at some stage. India’s deterrence strategy has had an impact, and there is now a clearer message that every act of terror will be treated as an act of war: #tilakdevasher1, Author He further

• #IndiaPakistan | The political ripples of West Asia war can be felt in India-Pak. The whole ecosystem wants India to out perform Pakistan in performative diplomacy Is 'Dalali' smart diplomacy? #rshivshankar decodes #TheHardFacts https://t.co/YTQLZpqT23

• Pakistan Caught Between Iran War, India Tensions & Afghan Border Conflicts #zakka_jacob decodes #Pakistan #IranWar #ShahbazSharif #DonaldTrump #PakistanIndiaTensions #PakistanEnergyCrisis https://t.co/1TuLC7IHhG

• #TheRightStand | What is the difference between what Pakistan does to India and what Iran is doing to Israel? The question is whether America and Israel should have been more prepared says #ARanganathan72 We are not getting sucked into this war, but we will see the aftermath in exports since those r

================================================================================
CLUSTER 1
================================================================================

• #BreakingNews | US President Donald Trump reiterates on ending India-Pakistan war on Pak PM's request during a press briefing #IranUSWar #Trump #Iran #US https://t.co/oT79hVDV90

• #BreakingNews | God is support US in this conflict, I have ended India Pakistan war because Pak PM asked me to: US President Donald Trump #IranIsrael #IranUSWar #Trump https://t.co/t8n9FWN38b

• #IndiaUS | ‘Threatened With 250% Tariff’: Trump Again Claims He Stopped India-Pakistan War https://t.co/ckUUCoIsvq

• ‘Trump Will Listen To Modi’: US War Expert Backs India For West Asia Mediation, Slams Pakistan Role #Trump #US #India #WestAsiaConflict https://t.co/kIRne2oI7I

• #BreakingNews | Abdul Basit Sparks Row With “Bomb Delhi, Mumbai” Remark Amid War Tensions; Former Pakistan Envoy Warns of Strikes on India in Extreme War Scenario #IndiaPakistan #AbdulBasit #BreakingNews #Geopolitics #NuclearThrea | #Sukanya_says https://t.co/zzDoK6ZF1l

================================================================================
CLUSTER 2
================================================================================

• #OperationSindoor: The Untold Story 88 hours that changed it all Military Analyst Tom Cooper talks about his book 88-Hours War: India-Pakistan War of May 2025 and Operation Sindoor and how India attacked Pakistan #Pakistan #India | #AnchorAnandN https://t.co/iiqB5humK5

• Watch the most definitive account of #OperationSindoor as it unfolded, as India changed the face of war that brought Pakistan on it knees. Take an immersive tour of what happened during those 88 hours Click here: https://t.co/uRZe2UE1Z1 https://t.co/Qh4IweAkEi

• From Drones Shattered To Terror Bases Attacked Watch the most definitive account of #OperationSindoor as it unfolded, as India changed the face of war that brought Pakistan on it knees. Watch #InsideOperationSindoor NOW: https://t.co/YMarESHMRA #Zakka_Jacob #AnchorAnandN https://t.co/uuWY30kMJ3

• From Drones Shattered To Terror Bases Attacked Watch the most definitive account of #OperationSindoor as it unfolded, as India changed the face of war that brought Pakistan on it knees. Watch #InsideOperationSindoor NOW: https://t.co/YMarESHMRA #Zakka_Jacob #AnchorAnandN https://t.co/E79n2aLOjU

• Watch the most definitive account of #OperationSindoor as it unfolded, as India changed the face of war that brought Pakistan on it knees. #InsideOperationSindoor: 88 Hours that redefined India! #operationsindoor #india #pakistan Watch here: https://t.co/YMarESHMRA

================================================================================
CLUSTER 3
================================================================================

• Did India lose the narrative war vs Pakistan? Defence expert Major Manik M Jolly (#Manik_M_Jolly) speaks with #ShivaniGupta_5 Watch #PlainSpeakPodcast on Saturday at 9:30 AM only on CNN-News18 Set reminder here: https://t.co/cw7L1uCKqs https://t.co/5EHpE1gYxs

• Did India lose the narrative war vs Pakistan? Defence expert Major Manik M Jolly (#Manik_M_Jolly) speaks with #ShivaniGupta_5 Watch #PlainSpeakPodcast on Saturday at 9:30 AM only on CNN-News18 Set reminder here: https://t.co/cw7L1uDig0 https://t.co/mt9eAtQGib

• Did India lose the narrative war vs Pakistan? Defence expert Major Manik M Jolly (#Manik_M_Jolly) speaks with #ShivaniGupta_5 Watch #PlainSpeakPodcast on Saturday at 9:30 AM only on CNN-News18 Set reminder here: https://t.co/cw7L1uDig0 https://t.co/gcqPUjCmwS

• Did India lose the narrative war vs Pakistan? Defence expert Major Manik M Jolly (#Manik_M_Jolly) speaks with #ShivaniGupta_5 Watch #PlainSpeakPodcast on Saturday at 9:30 AM only on CNN-News18 Set reminder here: https://t.co/cw7L1uCKqs https://t.co/Brc2Qg60PU

• Did India lose the narrative war vs Pakistan? Defence expert Major Manik M Jolly (#Manik_M_Jolly) speaks with #ShivaniGupta_5 Watch #PlainSpeakPodcast on Saturday at 9:30 AM only on CNN-News18 Set reminder here: https://t.co/cw7L1uCKqs https://t.co/fOJTlrDAVy

================================================================================
CLUSTER 4
================================================================================

• During the 1965 India-Pakistan war, Lal Bahadur Shastri and Ayub Khan faced off, leading to the Tashkent Declaration mediated by Alexei Kosygin, shaping future Indo-Pak diplomacy #IndiaPakistan #LalBahadurShastri https://t.co/Bq5fcb2NmD

• One little-known story from the 1971 India-Pakistan war shows how a single photograph helped break the enemy's will to fight #India #Pakistan https://t.co/WoYoo4Ofjf

• #IndiaPakistan | Maharaja Hari Singh sought Kashmir's independence in 1947, but Pakistan's invasion forced accession to India, sparking the enduring Kashmir dispute and the first India-Pakistan war https://t.co/cEA99uv5Gi

• #WATCH | India Recalls 1971 War To Highlight U.S Double Standards Over Russian Oil. Eastern Command Shares Newspaper Clipping Showing American Arms Supply To Pakistan Since 1954 #UnitedStates #IndianArmy #Pakistan (Video Source: Reuters) https://t.co/OIZ1Ol01gP

• Within an hour of MEA briefing on details of the understanding between India and Pakistan, Congress social media handles were talking about the 1971 war led by Indira Gandhi Writes: #_pallavighosh | #MEA #IndiraGandhi #1971War #PMModi https://t.co/5aM6w9vaQo https://t.co/OJ44P0iBtu

================================================================================
CLUSTER 5
================================================================================

• News 18 Daily Digest | Iran Confirms: Ali Larijani Dead | Pakistan Vs Afghanistan War | LPG Crisis In India | N18P #Iran #AliLarijani #BreakingNews #MiddleEastCrisis #IranWar #IsraelIran #WorldWar3 #Pakistan #Afghanistan #PakistanVsAfghanistan #KabulAttack https://t.co/vl3tB4NcTU

• Pakistan’s Defence Minister Khawaja Asif has said his country is “prepared for a two-front war,” citing potential tensions with India and ongoing border clashes with Afghanistan. #KhwajaAsif #Afghanistan #Pakistan #India https://t.co/r0MDYjsNV4

• Irfan Pathan responds to Shahid Afridi's remarks as their war of words intensifies ahead of the India vs Pakistan Asia Cup clash. #IrfanPathan #INDvsPAK #AsiaCup2025 #Cricket https://t.co/6HdxG1M5CT

• #OperationSindoor | "Pakistan has failed in any war that it fought with India. They withdrew in all wars and suffered a humiliating defeat": Major General (R) Indrabalan, Kargil war veteran Aviation expert Group Captain (R) M Vinod also shares his views #AnchorAnandN | #PahalgamTerrorAttack #IndiaPa

• #Live | India's reprisal plan: Mock drills now, onslaught next?; What to do/not do if war breaks? Ex-DG Home Guards explains. Pakistan UNSC 'flopshow', India has diplomatic edge? Watch #BrassTacks with #Zakka_Jacob https://t.co/ZRV9rHNDDm

================================================================================
CLUSTER 6
================================================================================

• #OpSindoor | For the first time, China has confirmed that it provided on-site technical support to Pakistan during its war with India https://t.co/Njp76QNyEf https://t.co/Q4AHy15fCC

• Pakistan is facing only India, while India is facing both China and Pakistan: Lt Gen. (R.) SL Narasimhan, Former Member, NSAB If intelligence is accurate, you have already won 80 percent of the war: #TinyDhillon, Former GOC #RShivshankar | #Budget2026india #Trump #NirmalaSitharaman #Budget2026 #TheH

• #EXCLUSIVE | US Defence Department-linked assessments have shed new light on how China and Pakistan are recalibrating their approach towards India through coordinated “grey-zone" strategies — operations designed to apply sustained pressure without crossing the threshold of open war. #manojkumargupta

• General Anil Chauhan called the China border dispute India's biggest challenge, cited Pakistan's proxy war, and discussed Op Sindoor and new war domains like cyber and space. #AnilChauhan #CDS #China #India https://t.co/66NypbzssH

• #AsimMunir | Pakistan's army chief Asim Munir threatens nuclear war over India's water control, but Bharat's military strength and strategic leverage expose his bluster #AnchorAnandN explains #TheRightStand #IndiaPakistan #Nuclear https://t.co/erJh8yFSdI

================================================================================
CLUSTER 7
================================================================================

• Bilawal Bhutto, ex-Pakistan foreign minister threatened India with war, including nuclear, over changes to the Indus Waters Treaty, accusing India of "barbarism." #BilawalBhutto #Pakistan #IndusWatersTreaty https://t.co/vQK5EjAPxm

• India-Pakistan water wars: With India tightening its grip on Chenab, Pakistan’s kharif sowing season could be very bleak as Pak faces water shortage #Ieshan_W speaks with the locals from Kashmir valley #Pakistan #IndusWaterTreaty #India #BrassTacks | #Zakka_Jacob https://t.co/RROwonCanv

• Indus Treaty In The Crosshairs: Is A Water War Brewing Between India And Pakistan? #AmanKayamHai_ with this episode of HomeWork #Induswaterstreaty #PMModi #India #pakistan #ShehbazSharif watch here: https://t.co/MsTqIjD5Ko

• #BreakingNews | India Pakistan water war escalates, India shuts all gates of Salal Dam on the Chenab River #TejinderSsodhi shares more details #RShivshankar | #IndusWaterTreaty #Chenab #Pakistan https://t.co/CkjgRVxhy1

• The Indus Waters Treaty — signed in 1960 — is often hailed as one of the most successful water-sharing agreements in history. Brokered by the World Bank between India and Pakistan, it has survived wars, terrorism, and decades of hostility. However, the Pahalgam terror attack on April 22 has once aga

In [37]:
from collections import Counter
import re

STOP_WORDS = {
    "the","and","for","that","with","this",
    "from","have","has","been","will","into",
    "after","their","about","they","were"
}

for cluster_id in sorted(messages["cluster"].unique()):

    cluster_messages = messages[
        messages["cluster"] == cluster_id
    ]

    words = []

    for text in cluster_messages["clean_text"]:

        tokens = re.findall(
            r"\b[a-zA-Z]{3,}\b",
            text.lower()
        )

        tokens = [
            t for t in tokens
            if t not in STOP_WORDS
        ]

        words.extend(tokens)

    common_words = Counter(words).most_common(10)

    print("\n")
    print("=" * 60)
    print(f"NARRATIVE CLUSTER {cluster_id}")
    print("=" * 60)
    print(common_words)

============================================================
NARRATIVE CLUSTER 0
============================================================
[('pakistan', 96), ('india', 91), ('war', 64), ('https', 60), ('operationsindoor', 15), ('are', 13), ('indiapakistan', 12), ('indiapakistanwar', 12), ('terror', 11), ('pahalgam', 11)]


============================================================
NARRATIVE CLUSTER 1
============================================================
[('india', 60), ('pakistan', 59), ('https', 45), ('trump', 43), ('war', 37), ('donaldtrump', 20), ('donald', 13), ('president', 11), ('claimed', 10), ('between', 10)]


============================================================
NARRATIVE CLUSTER 2
============================================================
[('operationsindoor', 31), ('https', 31), ('india', 30), ('pakistan', 23), ('war', 21), ('watch', 21), ('changed', 18), ('most', 17), ('definitive', 17), ('account', 17)]


============================================================
NARRATIVE CLUSTER 3
============================================================
[('https', 14), ('india', 8), ('pakistan', 8), ('war', 7), ('did', 6), ('lose', 6), ('narrative', 6), ('defence', 6), ('expert', 6), ('major', 6)]


============================================================
NARRATIVE CLUSTER 4
============================================================
[('india', 30), ('pakistan', 27), ('https', 22), ('war', 21), ('indiapakistanwar', 7), ('kashmir', 6), ('wars', 6), ('during', 5), ('known', 5), ('bangladesh', 5)]


============================================================
NARRATIVE CLUSTER 5
============================================================
[('india', 21), ('pakistan', 20), ('war', 17), ('https', 14), ('afghanistan', 4), ('kargil', 4), ('army', 4), ('breakingnews', 3), ('tensions', 3), ('all', 3)]


============================================================
NARRATIVE CLUSTER 6
============================================================
[('pakistan', 33), ('india', 29), ('china', 27), ('war', 19), ('https', 13), ('former', 11), ('army', 7), ('anchoranandn', 7), ('defence', 6), ('operationsindoor', 6)]


============================================================
NARRATIVE CLUSTER 7
============================================================
[('pakistan', 20), ('india', 18), ('water', 11), ('https', 9), ('war', 8), ('treaty', 8), ('indus', 7), ('induswatertreaty', 4), ('pahalgam', 4), ('move', 4)]

In [38]:
# ============================================================
# STEP 10: Build a Narrative Intelligence Report
# ============================================================

from collections import Counter
import re
import pandas as pd

# Better stop words for narrative keyword extraction
STOP_WORDS = {
    "the","and","for","that","with","this","from","have","has","been",
    "will","into","after","their","about","they","were","are","was",
    "you","your","but","not","all","can","more","said","says","over",
    "new","now","out","his","her","its","who","why","how","what"
}

def get_top_keywords(texts, top_n=8):
    """
    Extracts common meaningful keywords from a group of messages.
    """
    words = []

    for text in texts:
        tokens = re.findall(r"\b[a-zA-Z]{3,}\b", text.lower())
        tokens = [t for t in tokens if t not in STOP_WORDS]
        words.extend(tokens)

    return Counter(words).most_common(top_n)


narrative_reports = []

for cluster_id in sorted(messages["cluster"].unique()):

    cluster_df = messages[messages["cluster"] == cluster_id].copy()

    # Basic size and time metrics
    message_count = len(cluster_df)
    first_seen = cluster_df["date"].min()
    last_seen = cluster_df["date"].max()

    # Engagement metrics
    total_views = cluster_df["views"].fillna(0).sum()
    avg_views = cluster_df["views"].fillna(0).mean()
    total_forwards = cluster_df["forwards"].fillna(0).sum()

    # Keywords give us a rough narrative label
    keywords = get_top_keywords(cluster_df["clean_text"].tolist(), top_n=8)

    # Pick representative messages:
    # highest-viewed messages are often the most useful analyst examples
    representative = (
        cluster_df
        .sort_values("views", ascending=False)
        [["date", "views", "forwards", "clean_text", "message_link"]]
        .head(3)
    )

    narrative_reports.append({
        "cluster": cluster_id,
        "message_count": message_count,
        "first_seen": first_seen,
        "last_seen": last_seen,
        "total_views": total_views,
        "avg_views": round(avg_views, 2),
        "total_forwards": total_forwards,
        "keywords": keywords,
        "representative_messages": representative
    })


# Print the report in a readable analyst format
for report in narrative_reports:

    print("\n" + "=" * 90)
    print(f"NARRATIVE CLUSTER {report['cluster']}")
    print("=" * 90)

    print("Message count:", report["message_count"])
    print("First seen:", report["first_seen"])
    print("Last seen:", report["last_seen"])
    print("Total views:", report["total_views"])
    print("Average views:", report["avg_views"])
    print("Total forwards:", report["total_forwards"])

    print("\nTop keywords:")
    for word, count in report["keywords"]:
        print(f"  {word:<20} {count}")

    print("\nRepresentative messages:")
    for _, row in report["representative_messages"].iterrows():
        print("-" * 70)
        print("Date:", row["date"])
        print("Views:", row["views"])
        print("Forwards:", row["forwards"])
        print("Link:", row["message_link"])
        print("Text:", row["clean_text"][:500])

==========================================================================================
NARRATIVE CLUSTER 0
==========================================================================================
Message count: 59
First seen: 2025-03-16 13:06:39+00:00
Last seen: 2026-06-10 04:07:06+00:00
Total views: 272
Average views: 4.61
Total forwards: 0

Top keywords:
  pakistan             96
  india                91
  war                  64
  https                60
  operationsindoor     15
  indiapakistan        12
  indiapakistanwar     12
  terror               11

Representative messages:
----------------------------------------------------------------------
Date: 2025-07-29 13:48:14+00:00
Views: 11
Forwards: 0
Link: https://t.me/cnnnews18live/125262
Text: PM Narendra Modi said that Pakistan begged India to stop the war saying that "ab jyada maar jhelne ki takat nahi hai" #PMModi #OperationSindoor #IndiaPakistan #Ceasefire #BreakingNews #PahalgamTerrorAttack https://t.co/aTWx164bah https://t.co/skpOWamQgF
----------------------------------------------------------------------
Date: 2025-05-06 15:18:41+00:00
Views: 8
Forwards: 0
Link: https://t.me/cnnnews18live/96029
Text: #IndiaPakistan | Pakistan UNSC 'flop-show', does India has diplomatic edge? Pakistan's war-mongering continues #India #Pakistan #BrassTacks | #Zakka_Jacob https://t.co/BJkerSs43B
----------------------------------------------------------------------
Date: 2025-05-09 14:56:09+00:00
Views: 8
Forwards: 0
Link: https://t.me/cnnnews18live/97301
Text: Drones, missiles & firing: Pakistan used civilian flights as cover, kept airspace open even after attacking India India thwarts Pakistani drones, can Pakistan afford a war with India? India-Turkey ties at stake? #IndiaPakistan #BrassTacks | #Zakka_Jacob https://t.co/xs6q7XGwHx

==========================================================================================
NARRATIVE CLUSTER 1
==========================================================================================
Message count: 41
First seen: 2025-05-08 23:11:37+00:00
Last seen: 2026-04-06 18:50:57+00:00
Total views: 476
Average views: 11.61
Total forwards: 0

Top keywords:
  india                60
  pakistan             59
  https                45
  trump                43
  war                  37
  donaldtrump          20
  donald               13
  president            11

Representative messages:
----------------------------------------------------------------------
Date: 2025-08-11 16:24:15+00:00
Views: 61
Forwards: 0
Link: https://t.me/cnnnews18live/130450
Text: #Exclusive | These utterly irresponsible and nonsensical remarks by #AsimMunir are nothing more than a PR stunt for #Trump; a way to satisfy his ego and once again claim, without basis, that he “prevented” a nuclear war between India and Pakistan: Tom Cooper, Military Historian #RShivshankar | #TheHardFacts #OpSindoor #Pakistan #India #NuclearWar
----------------------------------------------------------------------
Date: 2025-08-15 00:15:21+00:00
Views: 46
Forwards: 0
Link: https://t.me/cnnnews18live/131733
Text: #WATCH | Washington DC | "6-7 planes were knocked out in India-Pakistan war, they were ready to go nuclear, we solved that" says US President Donald Trump #DonaldTrump #Credits #WarEnd #IndiaPakWar #RussiaUkrainewar #Putin #IndiaUSA #PMModi #OperationSindoor https://t.co/6IjHHfJZqj
----------------------------------------------------------------------
Date: 2025-08-13 02:17:38+00:00
Views: 43
Forwards: 0
Link: https://t.me/cnnnews18live/130867
Text: #Trending | The US State Department is patting itself on the back again for it, saying its diplomacy helped stop an India-Pakistan war #IndiaPakistanWar #IndiaPakistan #OperationSindoor #DonaldTrump #USPolitics #Defence #Viral https://t.co/kxw6Za9cG2

==========================================================================================
NARRATIVE CLUSTER 2
==========================================================================================
Message count: 20
First seen: 2025-05-08 03:12:11+00:00
Last seen: 2026-03-05 12:53:09+00:00
Total views: 68
Average views: 3.4
Total forwards: 0

Top keywords:
  operationsindoor     31
  https                31
  india                30
  pakistan             23
  war                  21
  watch                21
  changed              18
  most                 17

Representative messages:
----------------------------------------------------------------------
Date: 2025-05-08 03:12:11+00:00
Views: 6
Forwards: 0
Link: https://t.me/cnnnews18live/96517
Text: Operation Sindoor: Is War Close? A 25-minute precision strike at 1:05am that destroyed nine terror camps - India’s Operation Sindoor has well and truly shaken Pakistan. Tune in... #News18Podcasts #OperationSindoor #PahalgamTerrorAttack #IndiaPakistan https://t.co/ctxoAN6tCz https://t.co/9QsEq7VntO
----------------------------------------------------------------------
Date: 2025-05-31 04:55:21+00:00
Views: 5
Forwards: 0
Link: https://t.me/cnnnews18live/104599
Text: From Drones Shattered To Terror Bases Attacked Watch the most definitive account of #OperationSindoor as it unfolded, as India changed the face of war that brought Pakistan on it knees. Watch #InsideOperationSindoor NOW: https://t.co/YMarESHMRA #Zakka_Jacob #AnchorAnandN https://t.co/uuWY30kMJ3
----------------------------------------------------------------------
Date: 2025-05-30 13:40:37+00:00
Views: 4
Forwards: 0
Link: https://t.me/cnnnews18live/104424
Text: #OperationSindoor | Watch the most definitive account of #OperationSindoor as it unfolded, as India changed the face of war that brought Pakistan on it knees #InsideOperationSindoor tonight 8 PM #Zakka_Jacob #AnchorAnandN #RShivshankar Set reminder: https://t.co/YMarESHMRA https://t.co/IfK72ARhVD

==========================================================================================
NARRATIVE CLUSTER 3
==========================================================================================
Message count: 7
First seen: 2025-05-08 06:13:57+00:00
Last seen: 2025-06-07 03:47:52+00:00
Total views: 25
Average views: 3.57
Total forwards: 0

Top keywords:
  https                14
  india                8
  pakistan             8
  war                  7
  did                  6
  lose                 6
  narrative            6
  defence              6

Representative messages:
----------------------------------------------------------------------
Date: 2025-06-06 15:09:37+00:00
Views: 5
Forwards: 0
Link: https://t.me/cnnnews18live/107085
Text: Did India lose the narrative war vs Pakistan? Defence expert Major Manik M Jolly (#Manik_M_Jolly) speaks with #ShivaniGupta_5 Watch #PlainSpeakPodcast on Saturday at 9:30 AM only on CNN-News18 Set reminder here: https://t.co/cw7L1uCKqs https://t.co/fOJTlrDAVy
----------------------------------------------------------------------
Date: 2025-06-07 03:47:52+00:00
Views: 4
Forwards: 0
Link: https://t.me/cnnnews18live/107193
Text: Did India lose the narrative war vs Pakistan? Defence expert Major Manik M Jolly (#Manik_M_Jolly) speaks with #ShivaniGupta_5 Watch #PlainSpeakPodcast on Saturday at 9:30 AM only on CNN-News18 Set reminder here: https://t.co/cw7L1uCKqs https://t.co/5EHpE1gYxs
----------------------------------------------------------------------
Date: 2025-06-07 01:41:28+00:00
Views: 4
Forwards: 0
Link: https://t.me/cnnnews18live/107143
Text: Did India lose the narrative war vs Pakistan? Defence expert Major Manik M Jolly (#Manik_M_Jolly) speaks with #ShivaniGupta_5 Watch #PlainSpeakPodcast on Saturday at 9:30 AM only on CNN-News18 Set reminder here: https://t.co/cw7L1uDig0 https://t.co/gcqPUjCmwS

==========================================================================================
NARRATIVE CLUSTER 4
==========================================================================================
Message count: 18
First seen: 2024-12-16 01:46:17+00:00
Last seen: 2026-01-05 11:38:31+00:00
Total views: 96
Average views: 5.33
Total forwards: 0

Top keywords:
  india                30
  pakistan             27
  https                22
  war                  21
  indiapakistanwar     7
  kashmir              6
  wars                 6
  during               5

Representative messages:
----------------------------------------------------------------------
Date: 2025-08-05 16:52:08+00:00
Views: 35
Forwards: 0
Link: https://t.me/cnnnews18live/128254
Text: #WATCH | India Recalls 1971 War To Highlight U.S Double Standards Over Russian Oil. Eastern Command Shares Newspaper Clipping Showing American Arms Supply To Pakistan Since 1954 #UnitedStates #IndianArmy #Pakistan (Video Source: Reuters) https://t.co/OIZ1Ol01gP
----------------------------------------------------------------------
Date: 2025-05-11 08:43:13+00:00
Views: 7
Forwards: 0
Link: https://t.me/cnnnews18live/97909
Text: Within an hour of MEA briefing on details of the understanding between India and Pakistan, Congress social media handles were talking about the 1971 war led by Indira Gandhi Writes: #_pallavighosh | #MEA #IndiraGandhi #1971War #PMModi https://t.co/5aM6w9vaQo https://t.co/OJ44P0iBtu
----------------------------------------------------------------------
Date: 2025-05-09 08:49:34+00:00
Views: 6
Forwards: 0
Link: https://t.me/cnnnews18live/97138
Text: Veterans recall past India-Pakistan wars where civilian courage became a key defence, turning fear into resilience amid intense attacks and bombing raids #Blackout #IndiaPakistanWar #OperationSindoor #IndianArmy #Jodhpur https://t.co/4B1t14PBGV

==========================================================================================
NARRATIVE CLUSTER 5
==========================================================================================
Message count: 15
First seen: 2024-06-28 04:58:48+00:00
Last seen: 2026-03-18 01:51:27+00:00
Total views: 48
Average views: 3.2
Total forwards: 0

Top keywords:
  india                21
  pakistan             20
  war                  17
  https                14
  afghanistan          4
  kargil               4
  army                 4
  breakingnews         3

Representative messages:
----------------------------------------------------------------------
Date: 2026-03-18 01:51:27+00:00
Views: 6
Forwards: 0
Link: https://t.me/cnnnews18live/201621
Text: News 18 Daily Digest | Iran Confirms: Ali Larijani Dead | Pakistan Vs Afghanistan War | LPG Crisis In India | N18P #Iran #AliLarijani #BreakingNews #MiddleEastCrisis #IranWar #IsraelIran #WorldWar3 #Pakistan #Afghanistan #PakistanVsAfghanistan #KabulAttack https://t.co/vl3tB4NcTU
----------------------------------------------------------------------
Date: 2025-10-17 03:46:33+00:00
Views: 5
Forwards: 0
Link: https://t.me/cnnnews18live/153294
Text: Pakistan’s Defence Minister Khawaja Asif has said his country is “prepared for a two-front war,” citing potential tensions with India and ongoing border clashes with Afghanistan. #KhwajaAsif #Afghanistan #Pakistan #India https://t.co/r0MDYjsNV4
----------------------------------------------------------------------
Date: 2025-09-20 06:30:04+00:00
Views: 4
Forwards: 0
Link: https://t.me/cnnnews18live/145107
Text: Irfan Pathan responds to Shahid Afridi's remarks as their war of words intensifies ahead of the India vs Pakistan Asia Cup clash. #IrfanPathan #INDvsPAK #AsiaCup2025 #Cricket https://t.co/6HdxG1M5CT

==========================================================================================
NARRATIVE CLUSTER 6
==========================================================================================
Message count: 18
First seen: 2024-07-12 15:25:32+00:00
Last seen: 2026-05-08 14:33:16+00:00
Total views: 148
Average views: 8.22
Total forwards: 0

Top keywords:
  pakistan             33
  india                29
  china                27
  war                  19
  https                13
  former               11
  army                 7
  anchoranandn         7

Representative messages:
----------------------------------------------------------------------
Date: 2025-08-11 05:18:03+00:00
Views: 25
Forwards: 0
Link: https://t.me/cnnnews18live/130158
Text: Pakistan Field Marshal and Army chief Asim Munir issues open nuclear threat, says country will "take half the world down" with it if it faces an existential threat in a future war with India News18's #siddhantvm and #kaidensharmaa with details #kritsween | #indiapakistanconflict #AsimMunir #NuclearThreat
----------------------------------------------------------------------
Date: 2025-08-11 07:35:03+00:00
Views: 21
Forwards: 0
Link: https://t.me/cnnnews18live/130216
Text: Pakistan Field Marshal and Army chief Asim Munir issues open nuclear threat, says country will "take half the world down" with it if it faces an existential threat in a future war with India #indiapakistanconflict #AsimMunir #NuclearThreat https://t.co/w82jmxsdUH
----------------------------------------------------------------------
Date: 2025-09-05 12:31:43+00:00
Views: 20
Forwards: 0
Link: https://t.me/cnnnews18live/139718
Text: General Anil Chauhan called the China border dispute India's biggest challenge, cited Pakistan's proxy war, and discussed Op Sindoor and new war domains like cyber and space. #AnilChauhan #CDS #China #India https://t.co/66NypbzssH

==========================================================================================
NARRATIVE CLUSTER 7
==========================================================================================
Message count: 10
First seen: 2025-04-24 15:21:43+00:00
Last seen: 2025-08-11 17:15:02+00:00
Total views: 56
Average views: 5.6
Total forwards: 0

Top keywords:
  pakistan             20
  india                18
  water                11
  https                9
  war                  8
  treaty               8
  indus                7
  induswatertreaty     4

Representative messages:
----------------------------------------------------------------------
Date: 2025-08-11 17:15:02+00:00
Views: 27
Forwards: 0
Link: https://t.me/cnnnews18live/130462
Text: Bilawal Bhutto, ex-Pakistan foreign minister threatened India with war, including nuclear, over changes to the Indus Waters Treaty, accusing India of "barbarism." #BilawalBhutto #Pakistan #IndusWatersTreaty https://t.co/vQK5EjAPxm
----------------------------------------------------------------------
Date: 2025-05-26 03:43:20+00:00
Views: 4
Forwards: 0
Link: https://t.me/cnnnews18live/102503
Text: Indus Treaty In The Crosshairs: Is A Water War Brewing Between India And Pakistan? #AmanKayamHai_ with this episode of HomeWork #Induswaterstreaty #PMModi #India #pakistan #ShehbazSharif watch here: https://t.co/MsTqIjD5Ko
----------------------------------------------------------------------
Date: 2025-04-29 06:04:24+00:00
Views: 4
Forwards: 0
Link: https://t.me/cnnnews18live/93420
Text: The Indus Waters Treaty — signed in 1960 — is often hailed as one of the most successful water-sharing agreements in history. Brokered by the World Bank between India and Pakistan, it has survived wars, terrorism, and decades of hostility. However, the Pahalgam terror attack on April 22 has once again pushed this historic treaty into turbulent waters. #induswatertreaty #pakistan #india Source: Reuters

In [39]:
# ============================================================
# STEP 11: Narrative Importance Ranking
# ============================================================

import pandas as pd

summary_rows = []

for report in narrative_reports:

    # Simple narrative score
    score = (
        report["message_count"] * 1
        + report["avg_views"] * 0.01
        + report["total_forwards"] * 5
    )

    summary_rows.append({
        "cluster": report["cluster"],
        "messages": report["message_count"],
        "avg_views": report["avg_views"],
        "total_forwards": report["total_forwards"],
        "score": round(score, 2),
        "keywords": ", ".join(
            [w for w, c in report["keywords"][:5]]
        )
    })

narrative_summary = pd.DataFrame(summary_rows)

narrative_summary = narrative_summary.sort_values(
    "score",
    ascending=False
)

narrative_summary

,cluster,messages,avg_views,total_forwards,score,keywords
0,0,59,4.61,0,59.05,"pakistan, india, war, https, operationsindoor"
1,1,41,11.61,0,41.12,"india, pakistan, https, trump, war"
2,2,20,3.40,0,20.03,"operationsindoor, https, india, pakistan, war"
6,6,18,8.22,0,18.08,"pakistan, india, china, war, https"
4,4,18,5.33,0,18.05,"india, pakistan, https, war, indiapakistanwar"
5,5,15,3.20,0,15.03,"india, pakistan, war, https, afghanistan"
7,7,10,5.60,0,10.06,"pakistan, india, water, https, war"
3,3,7,3.57,0,7.04,"https, india, pakistan, war, did"

In [41]:
# ============================================================
# STEP 13: Top Messages
# ============================================================

top_messages = (
    messages
    .sort_values(
        "views",
        ascending=False
    )
    [[
        "date",
        "views",
        "forwards",
        "cluster",
        "clean_text",
        "message_link"
    ]]
    .head(20)
)

top_messages

,date,views,forwards,cluster,clean_text,message_link
53,2025-08-11 16:24:15+00:00,61,0,1,#Exclusive | These utterly irresponsible and n...,https://t.me/cnnnews18live/130450
49,2025-08-15 00:15:21+00:00,46,0,1,"#WATCH | Washington DC | ""6-7 planes were knoc...",https://t.me/cnnnews18live/131733
50,2025-08-13 02:17:38+00:00,43,0,1,#Trending | The US State Department is patting...,https://t.me/cnnnews18live/130867
48,2025-08-18 18:36:46+00:00,38,0,1,Trump has once again claimed that he stopped I...,https://t.me/cnnnews18live/133052
59,2025-08-05 16:52:08+00:00,35,0,4,#WATCH | India Recalls 1971 War To Highlight U...,https://t.me/cnnnews18live/128254
62,2025-07-28 16:25:29+00:00,34,0,1,Donald Trump yet again claimed that if he had ...,https://t.me/cnnnews18live/124828
52,2025-08-11 17:15:02+00:00,27,0,7,"Bilawal Bhutto, ex-Pakistan foreign minister t...",https://t.me/cnnnews18live/130462
57,2025-08-11 05:18:03+00:00,25,0,6,Pakistan Field Marshal and Army chief Asim Mun...,https://t.me/cnnnews18live/130158
60,2025-08-04 01:55:33+00:00,24,0,1,“Stopped a lot of wars…” Trump persists in cla...,https://t.me/cnnnews18live/127283
51,2025-08-12 08:36:05+00:00,22,0,1,A deepfake video falsely showing General Dwive...,https://t.me/cnnnews18live/130666
55,2025-08-11 07:35:03+00:00,21,0,6,Pakistan Field Marshal and Army chief Asim Mun...,https://t.me/cnnnews18live/130216
46,2025-09-05 03:38:39+00:00,21,0,1,#WATCH | While boasting about ending seven war...,https://t.me/cnnnews18live/139535
45,2025-09-05 12:31:43+00:00,20,0,6,General Anil Chauhan called the China border d...,https://t.me/cnnnews18live/139718
54,2025-08-11 13:47:52+00:00,18,0,6,#AsimMunir | Pakistan's army chief Asim Munir ...,https://t.me/cnnnews18live/130395
65,2025-07-09 02:20:04+00:00,16,0,1,"WATCH | ""Prevented and Ended War"": Rubio Backs...",https://t.me/cnnnews18live/118144
47,2025-08-27 06:23:36+00:00,16,0,1,"Before claiming he stopped a nuclear war, Trum...",https://t.me/cnnnews18live/136200
107,2025-05-10 18:35:47+00:00,15,0,6,'War Not India's Choice': NSA Doval To #China ...,https://t.me/cnnnews18live/97788
58,2025-08-08 08:38:36+00:00,13,0,1,"US Secretary of State Marco Rubio said, ""...Wh...",https://t.me/cnnnews18live/129364
56,2025-08-11 06:30:54+00:00,12,0,1,"During the same address, Munir also issued thr...",https://t.me/cnnnews18live/130190
61,2025-07-29 13:48:14+00:00,11,0,0,PM Narendra Modi said that Pakistan begged Ind...,https://t.me/cnnnews18live/125262